export const COUNTRY_CODES = [
  { name: "Afghanistan", code: "AF", dial_code: "+93", emoji: "🇦🇫" },
  { name: "Albania", code: "AL", dial_code: "+355", emoji: "🇦🇱" },
  { name: "Algeria", code: "DZ", dial_code: "+213", emoji: "🇩🇿" },
  { name: "American Samoa", code: "AS", dial_code: "+1 684", emoji: "🇦🇸" },
  { name: "Andorra", code: "AD", dial_code: "+376", emoji: "🇦🇩" },
  { name: "Angola", code: "AO", dial_code: "+244", emoji: "🇦🇴" },
  { name: "Anguilla", code: "AI", dial_code: "+1 264", emoji: "🇦🇮" },
  { name: "Antarctica", code: "AQ", dial_code: "+672", emoji: "🇦🇶" },
  { name: "Antigua and Barbuda", code: "AG", dial_code: "+1 268", emoji: "🇦🇬" },
  { name: "Argentina", code: "AR", dial_code: "+54", emoji: "🇦🇷" },
  { name: "Armenia", code: "AM", dial_code: "+374", emoji: "🇦🇲" },
  { name: "Aruba", code: "AW", dial_code: "+297", emoji: "🇦🇼" },
  { name: "Australia", code: "AU", dial_code: "+61", emoji: "🇦🇺" },
  { name: "Austria", code: "AT", dial_code: "+43", emoji: "🇦🇹" },
  { name: "Azerbaijan", code: "AZ", dial_code: "+994", emoji: "🇦🇿" },
  { name: "Bahamas", code: "BS", dial_code: "+1 242", emoji: "🇧🇸" },
  { name: "Bahrain", code: "BH", dial_code: "+973", emoji: "🇧🇭" },
  { name: "Bangladesh", code: "BD", dial_code: "+880", emoji: "🇧🇩" },
  { name: "Barbados", code: "BB", dial_code: "+1 246", emoji: "🇧🇧" },
  { name: "Belarus", code: "BY", dial_code: "+375", emoji: "🇧🇾" },
  { name: "Belgium", code: "BE", dial_code: "+32", emoji: "🇧🇪" },
  { name: "Belize", code: "BZ", dial_code: "+501", emoji: "🇧🇿" },
  { name: "Benin", code: "BJ", dial_code: "+229", emoji: "🇧🇯" },
  { name: "Bermuda", code: "BM", dial_code: "+1 441", emoji: "🇧🇲" },
  { name: "Bhutan", code: "BT", dial_code: "+975", emoji: "🇧🇹" },
  { name: "Bolivia", code: "BO", dial_code: "+591", emoji: "🇧🇴" },
  { name: "Bosnia and Herzegovina", code: "BA", dial_code: "+387", emoji: "🇧🇦" },
  { name: "Botswana", code: "BW", dial_code: "+267", emoji: "🇧🇼" },
  { name: "Brazil", code: "BR", dial_code: "+55", emoji: "🇧🇷" },
  { name: "British Indian Ocean Territory", code: "IO", dial_code: "+246", emoji: "🇮🇴" },
  { name: "Brunei Darussalam", code: "BN", dial_code: "+673", emoji: "🇧🇳" },
  { name: "Bulgaria", code: "BG", dial_code: "+359", emoji: "🇧🇬" },
  { name: "Burkina Faso", code: "BF", dial_code: "+226", emoji: "🇧🇫" },
  { name: "Burundi", code: "BI", dial_code: "+257", emoji: "🇧🇮" },
  { name: "Cambodia", code: "KH", dial_code: "+855", emoji: "🇰🇭" },
  { name: "Cameroon", code: "CM", dial_code: "+237", emoji: "🇨🇲" },
  { name: "Canada", code: "CA", dial_code: "+1", emoji: "🇨🇦" },
  { name: "Cape Verde", code: "CV", dial_code: "+238", emoji: "🇨🇻" },
  { name: "Cayman Islands", code: "KY", dial_code: "+ 1 345", emoji: "🇰🇾" },
  { name: "Central African Republic", code: "CF", dial_code: "+236", emoji: "🇨🇫" },
  { name: "Chad", code: "TD", dial_code: "+235", emoji: "🇹🇩" },
  { name: "Chile", code: "CL", dial_code: "+56", emoji: "🇨🇱" },
  { name: "China", code: "CN", dial_code: "+86", emoji: "🇨🇳" },
  { name: "Christmas Island", code: "CX", dial_code: "+61", emoji: "🇨🇽" },
  { name: "Cocos (Keeling) Islands", code: "CC", dial_code: "+61", emoji: "🇨🇨" },
  { name: "Colombia", code: "CO", dial_code: "+57", emoji: "🇨🇴" },
  { name: "Comoros", code: "KM", dial_code: "+269", emoji: "🇰🇲" },
  { name: "Congo", code: "CG", dial_code: "+242", emoji: "🇨🇬" },
  { name: "Congo, The Democratic Republic of the", code: "CD", dial_code: "+243", emoji: "🇨🇩" },
  { name: "Cook Islands", code: "CK", dial_code: "+682", emoji: "🇨🇰" },
  { name: "Costa Rica", code: "CR", dial_code: "+506", emoji: "🇨🇷" },
  { name: "Cote d'Ivoire", code: "CI", dial_code: "+225", emoji: "🇨🇮" },
  { name: "Croatia", code: "HR", dial_code: "+385", emoji: "🇭🇷" },
  { name: "Cuba", code: "CU", dial_code: "+53", emoji: "🇨🇺" },
  { name: "Cyprus", code: "CY", dial_code: "+357", emoji: "🇨🇾" },
  { name: "Czech Republic", code: "CZ", dial_code: "+420", emoji: "🇨🇿" },
  { name: "Denmark", code: "DK", dial_code: "+45", emoji: "🇩🇰" },
  { name: "Djibouti", code: "DJ", dial_code: "+253", emoji: "🇩🇯" },
  { name: "Dominica", code: "DM", dial_code: "+1 767", emoji: "🇩🇲" },
  { name: "Dominican Republic", code: "DO", dial_code: "+1 809", emoji: "🇩🇴" },
  { name: "Ecuador", code: "EC", dial_code: "+593", emoji: "🇪🇨" },
  { name: "Egypt", code: "EG", dial_code: "+20", emoji: "🇪🇬" },
  { name: "El Salvador", code: "SV", dial_code: "+503", emoji: "🇸🇻" },
  { name: "Equatorial Guinea", code: "GQ", dial_code: "+240", emoji: "🇬🇶" },
  { name: "Eritrea", code: "ER", dial_code: "+291", emoji: "🇪🇷" },
  { name: "Estonia", code: "EE", dial_code: "+372", emoji: "🇪🇪" },
  { name: "Ethiopia", code: "ET", dial_code: "+251", emoji: "🇪🇹" },
  { name: "Falkland Islands (Malvinas)", code: "FK", dial_code: "+500", emoji: "🇫🇰" },
  { name: "Faroe Islands", code: "FO", dial_code: "+298", emoji: "🇫🇴" },
  { name: "Fiji", code: "FJ", dial_code: "+679", emoji: "🇫🇯" },
  { name: "Finland", code: "FI", dial_code: "+358", emoji: "🇫🇮" },
  { name: "France", code: "FR", dial_code: "+33", emoji: "🇫🇷" },
  { name: "French Guiana", code: "GF", dial_code: "+594", emoji: "🇬🇫" },
  { name: "French Polynesia", code: "PF", dial_code: "+689", emoji: "🇵🇫" },
  { name: "Gabon", code: "GA", dial_code: "+241", emoji: "🇬🇦" },
  { name: "Gambia", code: "GM", dial_code: "+220", emoji: "🇬🇲" },
  { name: "Georgia", code: "GE", dial_code: "+995", emoji: "🇬🇪" },
  { name: "Germany", code: "DE", dial_code: "+49", emoji: "🇩🇪" },
  { name: "Ghana", code: "GH", dial_code: "+233", emoji: "🇬🇭" },
  { name: "Gibraltar", code: "GI", dial_code: "+350", emoji: "🇬🇮" },
  { name: "Greece", code: "GR", dial_code: "+30", emoji: "🇬🇷" },
  { name: "Greenland", code: "GL", dial_code: "+299", emoji: "🇬🇱" },
  { name: "Grenada", code: "GD", dial_code: "+1 473", emoji: "🇬🇩" },
  { name: "Guadeloupe", code: "GP", dial_code: "+590", emoji: "🇬🇵" },
  { name: "Guam", code: "GU", dial_code: "+1 671", emoji: "🇬🇺" },
  { name: "Guatemala", code: "GT", dial_code: "+502", emoji: "🇬🇹" },
  { name: "Guernsey", code: "GG", dial_code: "+44", emoji: "🇬🇬" },
  { name: "Guinea", code: "GN", dial_code: "+224", emoji: "🇬🇳" },
  { name: "Guinea-Bissau", code: "GW", dial_code: "+245", emoji: "🇬🇼" },
  { name: "Guyana", code: "GY", dial_code: "+592", emoji: "🇬🇾" },
  { name: "Haiti", code: "HT", dial_code: "+509", emoji: "🇭🇹" },
  { name: "Holy See (Vatican City State)", code: "VA", dial_code: "+379", emoji: "🇻🇦" },
  { name: "Honduras", code: "HN", dial_code: "+504", emoji: "🇭🇳" },
  { name: "Hong Kong", code: "HK", dial_code: "+852", emoji: "🇭🇰" },
  { name: "Hungary", code: "HU", dial_code: "+36", emoji: "🇭🇺" },
  { name: "Iceland", code: "IS", dial_code: "+354", emoji: "🇮🇸" },
  { name: "India", code: "IN", dial_code: "+91", emoji: "🇮🇳" },
  { name: "Indonesia", code: "ID", dial_code: "+62", emoji: "🇮🇩" },
  { name: "Iran, Islamic Republic of", code: "IR", dial_code: "+98", emoji: "🇮🇷" },
  { name: "Iraq", code: "IQ", dial_code: "+964", emoji: "🇮🇶" },
  { name: "Ireland", code: "IE", dial_code: "+353", emoji: "🇮🇪" },
  { name: "Isle of Man", code: "IM", dial_code: "+44", emoji: "🇮🇲" },
  { name: "Israel", code: "IL", dial_code: "+972", emoji: "🇮🇱" },
  { name: "Italy", code: "IT", dial_code: "+39", emoji: "🇮🇹" },
  { name: "Jamaica", code: "JM", dial_code: "+1 876", emoji: "🇯🇲" },
  { name: "Japan", code: "JP", dial_code: "+81", emoji: "🇯🇵" },
  { name: "Jersey", code: "JE", dial_code: "+44", emoji: "🇯🇪" },
  { name: "Jordan", code: "JO", dial_code: "+962", emoji: "🇯🇴" },
  { name: "Kazakhstan", code: "KZ", dial_code: "+7", emoji: "🇰🇿" },
  { name: "Kenya", code: "KE", dial_code: "+254", emoji: "🇰🇪" },
  { name: "Kiribati", code: "KI", dial_code: "+686", emoji: "🇰🇮" },
  { name: "Korea, Democratic People's Republic of", code: "KP", dial_code: "+850", emoji: "🇰🇵" },
  { name: "Korea, Republic of", code: "KR", dial_code: "+82", emoji: "🇰🇷" },
  { name: "Kuwait", code: "KW", dial_code: "+965", emoji: "🇰🇼" },
  { name: "Kyrgyzstan", code: "KG", dial_code: "+996", emoji: "🇰🇬" },
  { name: "Lao People's Democratic Republic", code: "LA", dial_code: "+856", emoji: "🇱🇦" },
  { name: "Latvia", code: "LV", dial_code: "+371", emoji: "🇱🇻" },
  { name: "Lebanon", code: "LB", dial_code: "+961", emoji: "🇱🇧" },
  { name: "Lesotho", code: "LS", dial_code: "+266", emoji: "🇱🇸" },
  { name: "Liberia", code: "LR", dial_code: "+231", emoji: "🇱🇷" },
  { name: "Libyan Arab Jamahiriya", code: "LY", dial_code: "+218", emoji: "🇱🇾" },
  { name: "Liechtenstein", code: "LI", dial_code: "+423", emoji: "🇱🇮" },
  { name: "Lithuania", code: "LT", dial_code: "+370", emoji: "🇱🇹" },
  { name: "Luxembourg", code: "LU", dial_code: "+352", emoji: "🇱🇺" },
  { name: "Macao", code: "MO", dial_code: "+853", emoji: "🇲🇴" },
  { name: "Macedonia, The Former Yugoslav Republic of", code: "MK", dial_code: "+389", emoji: "🇲🇰" },
  { name: "Madagascar", code: "MG", dial_code: "+261", emoji: "🇲🇬" },
  { name: "Malawi", code: "MW", dial_code: "+265", emoji: "🇲🇼" },
  { name: "Malaysia", code: "MY", dial_code: "+60", emoji: "🇲🇾" },
  { name: "Maldives", code: "MV", dial_code: "+960", emoji: "🇲🇻" },
  { name: "Mali", code: "ML", dial_code: "+223", emoji: "🇲🇱" },
  { name: "Malta", code: "MT", dial_code: "+356", emoji: "🇲🇹" },
  { name: "Marshall Islands", code: "MH", dial_code: "+692", emoji: "🇲🇭" },
  { name: "Martinique", code: "MQ", dial_code: "+596", emoji: "🇲🇶" },
  { name: "Mauritania", code: "MR", dial_code: "+222", emoji: "🇲🇷" },
  { name: "Mauritius", code: "MU", dial_code: "+230", emoji: "🇲🇺" },
  { name: "Mayotte", code: "YT", dial_code: "+262", emoji: "🇾🇹" },
  { name: "Mexico", code: "MX", dial_code: "+52", emoji: "🇲🇽" },
  { name: "Micronesia, Federated States of", code: "FM", dial_code: "+691", emoji: "🇫🇲" },
  { name: "Moldova, Republic of", code: "MD", dial_code: "+373", emoji: "🇲🇩" },
  { name: "Monaco", code: "MC", dial_code: "+377", emoji: "🇲🇨" },
  { name: "Mongolia", code: "MN", dial_code: "+976", emoji: "🇲🇳" },
  { name: "Montenegro", code: "ME", dial_code: "+382", emoji: "🇲🇪" },
  { name: "Montserrat", code: "MS", dial_code: "+1 664", emoji: "🇲🇸" },
  { name: "Morocco", code: "MA", dial_code: "+212", emoji: "🇲🇦" },
  { name: "Mozambique", code: "MZ", dial_code: "+258", emoji: "🇲🇿" },
  { name: "Myanmar", code: "MM", dial_code: "+95", emoji: "🇲🇲" },
  { name: "Namibia", code: "NA", dial_code: "+264", emoji: "🇳🇦" },
  { name: "Nauru", code: "NR", dial_code: "+674", emoji: "🇳🇷" },
  { name: "Nepal", code: "NP", dial_code: "+977", emoji: "🇳🇵" },
  { name: "Netherlands", code: "NL", dial_code: "+31", emoji: "🇳🇱" },
  { name: "Netherlands Antilles", code: "AN", dial_code: "+599", emoji: "🇦🇳" },
  { name: "New Caledonia", code: "NC", dial_code: "+687", emoji: "🇳🇨" },
  { name: "New Zealand", code: "NZ", dial_code: "+64", emoji: "🇳🇿" },
  { name: "Nicaragua", code: "NI", dial_code: "+505", emoji: "🇳🇮" },
  { name: "Niger", code: "NE", dial_code: "+227", emoji: "🇳🇪" },
  { name: "Nigeria", code: "NG", dial_code: "+234", emoji: "🇳🇬" },
  { name: "Niue", code: "NU", dial_code: "+683", emoji: "🇳🇺" },
  { name: "Norfolk Island", code: "NF", dial_code: "+672", emoji: "🇳🇫" },
  { name: "Northern Mariana Islands", code: "MP", dial_code: "+1 670", emoji: "🇲🇵" },
  { name: "Norway", code: "NO", dial_code: "+47", emoji: "🇳🇴" },
  { name: "Oman", code: "OM", dial_code: "+968", emoji: "🇴🇲" },
  { name: "Pakistan", code: "PK", dial_code: "+92", emoji: "🇵🇰" },
  { name: "Palau", code: "PW", dial_code: "+680", emoji: "🇵🇼" },
  { name: "Palestinian Territory, Occupied", code: "PS", dial_code: "+970", emoji: "🇵🇸" },
  { name: "Panama", code: "PA", dial_code: "+507", emoji: "🇵🇦" },
  { name: "Papua New Guinea", code: "PG", dial_code: "+675", emoji: "🇵🇬" },
  { name: "Paraguay", code: "PY", dial_code: "+595", emoji: "🇵🇾" },
  { name: "Peru", code: "PE", dial_code: "+51", emoji: "🇵🇪" },
  { name: "Philippines", code: "PH", dial_code: "+63", emoji: "🇵🇭" },
  { name: "Pitcairn", code: "PN", dial_code: "+872", emoji: "🇵🇳" },
  { name: "Poland", code: "PL", dial_code: "+48", emoji: "🇵🇱" },
  { name: "Portugal", code: "PT", dial_code: "+351", emoji: "🇵🇹" },
  { name: "Puerto Rico", code: "PR", dial_code: "+1 787", emoji: "🇵🇷" },
  { name: "Qatar", code: "QA", dial_code: "+974", emoji: "🇶🇦" },
  { name: "Reunion", code: "RE", dial_code: "+262", emoji: "🇷🇪" },
  { name: "Romania", code: "RO", dial_code: "+40", emoji: "🇷🇴" },
  { name: "Russian Federation", code: "RU", dial_code: "+7", emoji: "🇷🇺" },
  { name: "Rwanda", code: "RW", dial_code: "+250", emoji: "🇷🇼" },
  { name: "Saint Helena", code: "SH", dial_code: "+290", emoji: "🇸🇭" },
  { name: "Saint Kitts and Nevis", code: "KN", dial_code: "+1 869", emoji: "🇰🇳" },
  { name: "Saint Lucia", code: "LC", dial_code: "+1 758", emoji: "🇱🇨" },
  { name: "Saint Pierre and Miquelon", code: "PM", dial_code: "+508", emoji: "🇵🇲" },
  { name: "Saint Vincent and the Grenadines", code: "VC", dial_code: "+1 784", emoji: "🇻🇨" },
  { name: "Samoa", code: "WS", dial_code: "+685", emoji: "🇼🇸" },
  { name: "San Marino", code: "SM", dial_code: "+378", emoji: "🇸🇲" },
  { name: "Sao Tome and Principe", code: "ST", dial_code: "+239", emoji: "🇸🇹" },
  { name: "Saudi Arabia", code: "SA", dial_code: "+966", emoji: "🇸🇦" },
  { name: "Senegal", code: "SN", dial_code: "+221", emoji: "🇸🇳" },
  { name: "Serbia", code: "RS", dial_code: "+381", emoji: "🇷🇸" },
  { name: "Seychelles", code: "SC", dial_code: "+248", emoji: "🇸🇨" },
  { name: "Sierra Leone", code: "SL", dial_code: "+232", emoji: "🇸🇱" },
  { name: "Singapore", code: "SG", dial_code: "+65", emoji: "🇸🇬" },
  { name: "Slovakia", code: "SK", dial_code: "+421", emoji: "🇸🇰" },
  { name: "Slovenia", code: "SI", dial_code: "+386", emoji: "🇸🇮" },
  { name: "Solomon Islands", code: "SB", dial_code: "+677", emoji: "🇸🇧" },
  { name: "Somalia", code: "SO", dial_code: "+252", emoji: "🇸🇴" },
  { name: "South Africa", code: "ZA", dial_code: "+27", emoji: "🇿🇦" },
  { name: "South Georgia and the South Sandwich Islands", code: "GS", dial_code: "+500", emoji: "🇬🇸" },
  { name: "Spain", code: "ES", dial_code: "+34", emoji: "🇪🇸" },
  { name: "Sri Lanka", code: "LK", dial_code: "+94", emoji: "🇱🇰" },
  { name: "Sudan", code: "SD", dial_code: "+249", emoji: "🇸🇩" },
  { name: "Suriname", code: "SR", dial_code: "+597", emoji: "🇸🇷" },
  { name: "Svalbard and Jan Mayen", code: "SJ", dial_code: "+47", emoji: "🇸🇯" },
  { name: "Swaziland", code: "SZ", dial_code: "+268", emoji: "🇸🇿" },
  { name: "Sweden", code: "SE", dial_code: "+46", emoji: "🇸🇪" },
  { name: "Switzerland", code: "CH", dial_code: "+41", emoji: "🇨🇭" },
  { name: "Syrian Arab Republic", code: "SY", dial_code: "+963", emoji: "🇸🇾" },
  { name: "Taiwan, Province of China", code: "TW", dial_code: "+886", emoji: "🇹🇼" },
  { name: "Tajikistan", code: "TJ", dial_code: "+992", emoji: "🇹🇯" },
  { name: "Tanzania, United Republic of", code: "TZ", dial_code: "+255", emoji: "🇹🇿" },
  { name: "Thailand", code: "TH", dial_code: "+66", emoji: "🇹🇭" },
  { name: "Timor-Leste", code: "TL", dial_code: "+670", emoji: "🇹🇱" },
  { name: "Togo", code: "TG", dial_code: "+228", emoji: "🇹🇬" },
  { name: "Tokelau", code: "TK", dial_code: "+690", emoji: "🇹🇰" },
  { name: "Tonga", code: "TO", dial_code: "+676", emoji: "🇹🇴" },
  { name: "Trinidad and Tobago", code: "TT", dial_code: "+1 868", emoji: "🇹🇹" },
  { name: "Tunisia", code: "TN", dial_code: "+216", emoji: "🇹🇳" },
  { name: "Turkey", code: "TR", dial_code: "+90", emoji: "🇹🇷" },
  { name: "Turkmenistan", code: "TM", dial_code: "+993", emoji: "🇹🇲" },
  { name: "Turks and Caicos Islands", code: "TC", dial_code: "+1 649", emoji: "🇹🇨" },
  { name: "Tuvalu", code: "TV", dial_code: "+688", emoji: "🇹🇻" },
  { name: "Uganda", code: "UG", dial_code: "+256", emoji: "🇺🇬" },
  { name: "Ukraine", code: "UA", dial_code: "+380", emoji: "🇺🇦" },
  { name: "United Arab Emirates", code: "AE", dial_code: "+971", emoji: "🇦🇪" },
  { name: "United Kingdom", code: "GB", dial_code: "+44", emoji: "🇬🇧" },
  { name: "United States", code: "US", dial_code: "+1", emoji: "🇺🇸" },
  { name: "United States Minor Outlying Islands", code: "UM", dial_code: "+1", emoji: "🇺🇲" },
  { name: "Uruguay", code: "UY", dial_code: "+598", emoji: "🇺🇾" },
  { name: "Uzbekistan", code: "UZ", dial_code: "+998", emoji: "🇺🇿" },
  { name: "Vanuatu", code: "VU", dial_code: "+678", emoji: "🇻🇺" },
  { name: "Venezuela", code: "VE", dial_code: "+58", emoji: "🇻🇪" },
  { name: "Viet Nam", code: "VN", dial_code: "+84", emoji: "🇻🇳" },
  { name: "Virgin Islands, British", code: "VG", dial_code: "+1 284", emoji: "🇻🇬" },
  { name: "Virgin Islands, U.S.", code: "VI", dial_code: "+1 340", emoji: "🇻🇮" },
  { name: "Wallis and Futuna", code: "WF", dial_code: "+681", emoji: "🇼🇫" },
  { name: "Western Sahara", code: "EH", dial_code: "+212", emoji: "🇪🇭" },
  { name: "Yemen", code: "YE", dial_code: "+967", emoji: "🇾🇪" },
  { name: "Zambia", code: "ZM", dial_code: "+260", emoji: "🇿🇲" },
  { name: "Zimbabwe", code: "ZW", dial_code: "+263", emoji: "🇿🇼" }
];
